/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class InfluxDbClient {
  constructor(addr: string, token?: string | undefined | null)
  queryBatch(database: string, query: string, type: QueryType): Promise<QueryResultByBatch>
}
export type InfluxDBClient = InfluxDbClient

export declare class QueryResultByBatch {
  next(): Promise<Array<ReturnDataType> | null>
}

export declare class QueryResultByRow {

}

export declare const enum QueryType {
  Sql = 'sql',
  Flux = 'flux'
}

export type ReturnDataType =
  Record<string, any | undefined | null>
